### PR TITLE
Add poll API support for nuttx platform

### PR DESCRIPTION
**Pull request by topelinux**
Add uv poll API support for nuttx platform

### CODE REVIEW

**Comment by yichoi** [comment]
@topelinux Please add [DCO](https://github.com/Samsung/iotjs/wiki/IoT.js-Developer's-Certificate-of-Origin-1.0)

**Comment by glistening** [comment]
Thank you for PR. We currently don't run tests on nuttx automatically. So I want to make sure. Do you have testcases for your added functions? If so, could you include the testcases in this commit in suitable places in test directory ?

**Comment by topelinux** [comment]
I am afraid i don't have test case, do you have any guide for how to enable
test case for nuttx platform and run it automatically?


2016-11-17 12:55 GMT+08:00 Sanggyu Lee <notifications@github.com>:

**Comment by glistening** [comment]
Currently we don't have/provide to run testcase automatically. It is the reason we don't test in every PR automatically. I found the guide in https://github.com/Samsung/libtuv/wiki/How-to-Build. You need stm32f4 board with nuttx installed. For my case, since I mainly use/modify libtuv for iot.js. I make nuttx and iot.js binary image and test in that environment. You can refer the iot.js repository and manuals. Thank you.

**Pull request closed without merging**
