### PR TITLE
Add Position-Independent-Code (PIC) Library

### PR DESCRIPTION
**Pull request by chenwei-tw**
Add the PIC Library, which can be used to link with other libraries and produce the final shared library.

To avoid confusion with static linked library, I name it "libtuv.o". Any suggestion? Thanks!

libtuv-DCO-1.0-Signed-off-by: zhenwei zhenwei.tw@gmail.com

### CODE REVIEW

**Comment by hs0225** [comment]
@chenwei-tw I close this PR since you have not reacted for a long time. You can reopen it at any time.

**Comment by marktwtn** [comment]
Hi @hs0225 , I would like to create another pull request for creating the PIC library.

Shall we discuss and figure out a conclusion in here first?

**Comment by marktwtn** [comment]
The generated library is neither static library nor shared library.
It is much like a collection of position indepent object code.
Though I do not come out with a better file extension name, the `libtuv.o` might be cofusing?

I think adding option about `COMPILER_FLAGS` in Makefile is simpler.
But the generated file suffix should be determined first.

**Comment by LaszloLango** [comment]
@marktwtn hi, I don't have strong preferences, `libtuv.o` or `libtuv.so` are both good to me.

**Comment by marktwtn** [comment]
I think this pull request can be merged without any problem.

The PIC library for linking with other libraries and produce the final shared library is a special one.
Adding option about `COMPILE_FLAGS` in Makefile is not enough.
It should be taken care independently in `cmake/libtuv.cmake`.

**Pull request closed without merging**
