### PR TITLE
Update tuv based on uv (1.10.1)

### PR DESCRIPTION
**Pull request by glistening**
1. Back to the source structure of uv

- Remove uv_platform.h, uv__platform.h, uv__unix_platform.h, uv_extension.h,
 uv__unix_extension.h, ...

 : Different source structure make us hard to upgrade uv.
 : Remove redundant code in above files.
  - QUEUE does not require initialization before QUEUE_INSERT_HEAD
  - static integer does not require initialization of zero

2. Differences between uv 1.10.1 and tuv

- Nuttx platform support
- Many code (that assumes unix, especially linux) are removed
- Resource cleanup on exit is added (as form of _deinit)
- CMake scripts support
- Tuv test runner
 : We cannot use uv's test since it assumes fork. Thus I reuse tuv tests.

### CODE REVIEW

**Comment by nova0821** [comment]
Hello, I think below is needed:

1. Add license which is modified.
2. Remove codes which are related 'IPv6'

Thanks.

**Comment by glistening** [comment]
I added license to modified files. And I make check whether ipv6 codes are removed in inet.c.

**Comment by hs0225** [comment]
LGTM

**Comment by nova0821** [comment]
LGTM

**Pull request merged**
