### PR TITLE
Add uv_is_readable, uv_is_writable

### PR DESCRIPTION
**Pull request by bsdelf**
Import uv_is_readable, uv_is_writable from libuv.

### CODE REVIEW

**Comment by LaszloLango** [comment]
LGTM

**Comment by daeyeon** [comment]
Do we have the signed-off-by guidance for libtuv? DCO looks missing here.

**Comment by daeyeon** [comment]
I'm neutral on this. I once heard that we have a strategy to make the minimum necessary modifications on `libtuv` for easy-maintenance.

**Comment by glistening** [comment]
@daeyeon You're right. We have the strategy for maintenance. However, for this case, uv_is_readable and uv_is_writable come from uv. We removed the code to reduce binary size. (both of code is not used in iotjs). But the binary size increase must be a few bytes. So I would like to approve this PR.

**Comment by yichoi** [comment]
LGTM

**Comment by glistening** [comment]
I've measured binary size increment by this PR. It is size of libtuv.a after stripping from release build binary.

```
arm-linux : 37520 -> 37644 (124 bytes)
arm-nuttx : 31918 -> 32062 (144 bytes)
```

**Pull request merged**
