### PR TITLE
Memory optimization of timer

### PR DESCRIPTION
**Pull request by LaszloLango**
libtuv-DCO-1.0-Signed-off-by: László Langó llango.u-szeged@partner.samsung.com

### CODE REVIEW

**Comment by LaszloLango** [comment]
Related IoT.js issue: https://github.com/Samsung/iotjs/issues/725

**Comment by glistening** [comment]
@LaszloLango I like this patch! For maintainability, could you leave comments or enclose these changes with a flag so that we can easily identify what is our changes and what is libuv's changes?

option 1. use comment
```
// libtuv change @20170425-laszlolango
```
option 2. use flag
```
#ifdef TUV_MEMORY_OPTIMIZE
// your enhanced code
#else 
 // original code
#endif
```
and #define TUV_MEMORY_OPTIMIZE in common header like ( uv.h )

I like both. But slightly prefer to option 2.
If you have other idea, I would respect your idea.

**Comment by LaszloLango** [comment]
@glistening I've updated the PR with a guard around the new code as you suggested, but I'm not sure that it will make the upstream easier. The biggest problem with libuv and the current version of libtuv is that they are not designed for constraint systems. It is quite obvious that the goal was high performance and not the memory usage or binary size. IMHO we should make serious rewrites in the libtuv to make it suitable for constraint devices like STM32f4-discovery.

**Comment by yichoi** [comment]
@LaszloLango I agree with you. I could not decide yet what we want to achieve with libtuv between maintainability and performance. As for now, we are inclined to maintainability a little bit more since I am expecting we will handle more targets and OSes for the future.

**Comment by glistening** [comment]
@LaszloLango Thank you for enclosing with guards. This guards will be very helpful when I upstream. Please give us the rewrite point. If there is a considerable gains, we would rewrite. And I like the new guard name than my suggested name. :)

**Comment by yichoi** [comment]
LGTM

**Pull request merged**
